### PR TITLE
Fix run single

### PR DESCRIPTION
**Pull request by gauntl3t12**
It was found in my production environment that the cron task would not run unless the log file was being tailed. Updates made accordingly.

### CODE REVIEW

**Comment by gauntl3t12** [comment]
Note all of my CI's will fail as I rightfully cannot push to your docker registry.

**Comment by gauntl3t12** [comment]
> Note all of my CI's will fail as I rightfully cannot push to your docker registry.

I believe I found a fix for this which also makes forks easier. Go to [this link](https://github.com/Martlark/pg_dump/settings/variables/actions). Add the `Repository Variable`: `DOCKER_REG` and set the value to `martlark`.

**Comment by Martlark** [comment]
Good work.  I'll look at it in the next couple of days.

**Comment by Martlark** [comment]
> > Note all of my CI's will fail as I rightfully cannot push to your docker registry.
> 
> I believe I found a fix for this which also makes forks easier. Go to [this link](https://github.com/Martlark/pg_dump/settings/variables/actions). Add the `Repository Variable`: `DOCKER_REG` and set the value to `martlark`.

I've added that repository variable. Builds are still failing though

**Comment by gauntl3t12** [comment]
> > > Note all of my CI's will fail as I rightfully cannot push to your docker registry.
> > 
> > 
> > I believe I found a fix for this which also makes forks easier. Go to [this link](https://github.com/Martlark/pg_dump/settings/variables/actions). Add the `Repository Variable`: `DOCKER_REG` and set the value to `martlark`.
> 
> I've added that repository variable. Builds are still failing though

Saw that. I will take a look next week. Forks have odd rules with which variables get used. On GitLab it would use yours, but I’ll do some investigation.

**Comment by gauntl3t12** [comment]
Actually @Martlark it looks like you didn’t set the variable correctly. If you look at the failed jobs, it doesn’t have the folder. It’s “/pg-dump”

**Comment by Martlark** [comment]
[cid:28654002-16e5-4dd4-a030-56acdb203225]
Looks OK to me.


Andrew Rowe
m 04 381 777 86

________________________________

**Comment by gauntl3t12** [comment]
If the "cid" was supposed to be a picture, I can't see it. This is what I have for my settings menu. 
image

**Comment by Martlark** [comment]
[cid:82e21198-a48c-4e12-9938-ec6f506f8d21]
This is what it looks like to me

Andrew Rowe
m 04 381 777 86

________________________________

**Comment by gauntl3t12** [comment]
> [cid:82e21198-a48c-4e12-9938-ec6f506f8d21] This is what it looks like to me Andrew Rowe m [04 381 777 86](tel:04%20381%20777%2086)
> […](#)
Unfortunately the email replies aren’t working for pictures

**Comment by Martlark** [comment]
There are errors on the checks, if you can fix please

**Comment by gauntl3t12** [comment]
Please provide a photo showing the projects action environment like I did for my fork above. I believe there may be an issue with the projects environment causing the failures.

**Pull request merged**
